// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rJH19fnq0COOZ1mOMOf7vro9sFkhslc',
    appId: '1:874329281248:ios:35f5b09b1ce9a8a4c77685',
    messagingSenderId: '874329281248',
    projectId: 'taskfireinsta',
    storageBucket: 'taskfireinsta.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rJH19fnq0COOZ1mOMOf7vro9sFkhslc',
    appId: '1:874329281248:ios:35f5b09b1ce9a8a4c77685',
    messagingSenderId: '874329281248',
    projectId: 'taskfireinsta',
    storageBucket: 'taskfireinsta.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDovtCwJa51KUhXLJ_s-LYQD3huJeWaD2M',
    appId: '1:874329281248:web:30283a03f5daf8e5c77685',
    messagingSenderId: '874329281248',
    projectId: 'taskfireinsta',
    authDomain: 'taskfireinsta.firebaseapp.com',
    storageBucket: 'taskfireinsta.firebasestorage.app',
    measurementId: 'G-8ZVKS9Q12S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALhnwufkxociXClziKl_1syJqHjzobAPQ',
    appId: '1:874329281248:android:c6b03ad1c211168dc77685',
    messagingSenderId: '874329281248',
    projectId: 'taskfireinsta',
    storageBucket: 'taskfireinsta.firebasestorage.app',
  );

}